### ISSUE TITLE
初期状態に戻したい

### ISSUE THREAD

**Issue by yoshi0222** [Clipy/Clipy#101]
私の不手際なのですが、教えて下さい。
本アプリケーションを利用していたのですが、設定方法が悪くタスクバーにアイコンが表示されなくなり、各ショートカットキーにつきましても失念しました。

お手数ですが、設定初期化する方法はあるのでしょうか？

**Comment by Econa77** [comment]
Clipyご使用ありがとうございます。

初期化の方法は以下の３通りが簡単かと思いますので、どれかをお試し下さい。

1. 「AppCleaner」等のアプリ削除ツールを使用してClipyを削除した後に再度インストール
 http://itea40.jp/application/mac-utilities/appcleaner/

2. ターミナル等をご使用していただける方ですと以下のコマンドを実行して再起動
 `defaults delete com.clipy-app.Clipy`

3. ショートカットキーの設定をいじっていないのでしたデフォルトのメニュ呼び出しが `Command + Shift + v` ですので、メニューを起動し設定を変更

上記の方法で解決しないようでしたら再度御連絡いただけると助かります。

**Comment by yoshi0222** [comment]
早速のご返信ありがとうございます。

> ターミナル等をご使用していただける方ですと以下のコマンドを実行して再起動
> defaults delete com.clipy-app.Clipy
上記、方法後に再インストールすることで初期状態に戻すことが出来ました。
ありがとうございました。
