### ISSUE TITLE
Image previews do not display

### ISSUE THREAD

**Issue by afreet** [Clipy/Clipy#115]
I'm using Clipy v1.1.0 on MacOS Sierra 10.12.1

When I copy an image to the clipboard, and then use Clipy, I don't see a preview for that image in the menu.  It does seem to paste successfully if I select it from the menu, though.

**Comment by Econa77** [comment]
@afreet The same issue was able to reproduce.
I fix as soon as possible.

Thank you for your report 😄

**Comment by Econa77** [comment]
On MacOS Sierra, changed pasteboard format for image.
For more research and to Fixing it 😢

**Comment by Econa77** [comment]
@afreet Fixed issue. Please wait a little more as it will be reflected in the next release.
Thanks for your report 👍
