### ISSUE TITLE
unsolicited HTTPS connections to amazonaws.com

### ISSUE THREAD

**Issue by vollkommenheit** [Clipy/Clipy#118]
Why is Clipy opening HTTPS connections, seemingly almost every minute, to either of the following addresses, even though "automatically check for update" is disabled?

ec2-54-235-114-192.compute-1.amazonaws.com
ec2-23-23-110-243.compute-1.amazonaws.com

I also see HTTPS connections to 104.27.179.207 and ec2-23-23-110-243.compute-1.amazonaws.com, when a check update is manually requested.

I did a cursory search (with grep) for those addresses in all the files of the Clipy source code, without turning anything up. Where are those addresses specified?

**Comment by Econa77** [comment]
@vollkommenheit Clipy is using [fabric](https://fabric.io) to collect crash and error log.
Those aws addresses is connect fabric services.

For example.
- #116 is automatically generate crash issue by crashlytics.
- https://github.com/Clipy/Clipy/blob/master/Clipy/AppDelegate.swift#L108 For collect error log.

However, I'm sorry to have arbitrarily collected logs. Next Clipy release, we add collect log option at preference window. Clipy release binaries is no change open source code.

Thank you reporting issue, and using Clipy.

**Comment by vollkommenheit** [comment]
Thanks for clarifying.
