### ISSUE TITLE
ペースト後の消去

### ISSUE THREAD

**Issue by wakuya** [Clipy/Clipy#124]
いつも便利に使わせていただいております。

一点要望なのですが、
ペースト後にペーストアイテムを履歴より消去できるオプションを実装できないでしょうか。

流し込み作業などでどこまでペーストしたのかがわかると便利なので…。

ご検討よろしくお願い致します。

**Comment by Econa77** [comment]
@wakuya Clipy使用していただいてありがとうございます。

履歴の削除機能はなんらかの形で早いタイミングでリリース予定です。
ペースト時の同時削除は履歴削除機能よりも遅れますがカスタムアクションとして導入できるように検討させていただきます。

ご要望ありがとうございます。

**Comment by wakuya** [comment]
ご検討ありがとうございます。
ますます追加勝手が良くなりますね。
楽しみにしております。

**Comment by Econa77** [comment]
@wakuya 実装遅くなってしまいすいません。先程履歴の削除機能をβ機能として実装し [v1.1.4](https://github.com/Clipy/Clipy/releases/tag/1.1.4) をリリースしました。
設定画面のベータ機能タブより設定して使用することができますので、ぜひお試しください。

不具合等ありましたらissue等また立てていただけるとありがたいです 🙏

**Comment by wakuya** [comment]
Econa77さま

ご連絡ありがとうございます。
そして素晴らしい機能の追加、ありがとうございます。
テスト動作したところイメージ通りのコピペができてとても満足しております。
今後ともどうぞよろしくお願いいたします。
