### ISSUE TITLE
please add an option for increasing of width of pop-up or to show tooltip without delay

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Clipy/Clipy#145]
Hi, thank you for your great app, it is convenient for me.

**Comment by Econa77** [comment]
@vitaly-zdanevich Sorry for the late reply

In the current AppKit menu cannot customize the behavior of the tooltip.
Please wait for the update as we will update it so that can customize it in the future.

Thank you for using clipy 😄

**Comment by kallebornemark** [comment]
I am also very keen on this. Not seing more than a few characters in the list is almost a dealbreaker for me, as many items in the populated list are often similar and hard to distinguish from eachother without seing them in full length.

Is this still something that's not possible to implement?
