### ISSUE TITLE
1Password browser plugins not excluded

### ISSUE THREAD

**Issue by OrcaXS** [Clipy/Clipy#149]
I added 1Password.app to the exclusion list, but only the main 1Password app was excluded, browser plugins were not. However, some other clipboard management apps, like Pastebot can ignore 1Password browser plugins by default. Is it possible to implement this feature?

Thanks!

**Comment by Econa77** [comment]
@OrcaXS Thanks for the issue. This is a known problem 😢 
I am looking for a solution so please wait a little more. We will respond in the near future :)

Thanks 👍

**Comment by Econa77** [comment]
@OrcaXS Fix to excluding 1Password.app browser extensions. We will upgrade at the end of this month so please wait a bit more 😄
