### ISSUE TITLE
Crash when adding exclude applications in Preferences (V1.1.2)

### ISSUE THREAD

**Issue by henng** [Clipy/Clipy#153]
Clipy exit unexpectedly when adding exclude applications.

**Comment by Econa77** [comment]
@henng Thanks for the report 👍  Would you please send a log as I want detailed information on the crash.

http://apple.stackexchange.com/questions/26480/where-can-i-find-my-crash-logs

Location of crash log:
`~/Library/Logs/DiagnosticReports/`
Log file name:
`com.clipy.Clipy_xxx` or `Clipy_xxx`

**Comment by henng** [comment]
OK. Here's the crash log. @Econa77 

[Clipy_2017-02-21-211925_myMac.crash.zip](https://github.com/Clipy/Clipy/files/799561/Clipy_2017-02-21-211925_myMac.crash.zip)

**Comment by haenzet** [comment]
Hi,

I do still see this problem with KeePassXC. Please find attached my crash log.

KR haenzet

[Clipy_2017-09-05-135832_omni.crash.zip](https://github.com/Clipy/Clipy/files/1277307/Clipy_2017-09-05-135832_omni.crash.zip)

**Comment by Ariela1127** [comment]
Hi there

I also experience this issue when I try to add 1Password 6 to the excluded applications.

[Clipy Logs.zip](https://github.com/Clipy/Clipy/files/1313476/Clipy.Logs.zip)

**Comment by Econa77** [comment]
@henng @haenzet @Ariela1127 Sorry for late release 😢  We fixed this issue and released [v1.1.4](https://github.com/Clipy/Clipy/releases/tag/1.1.4) 🎉
Plase try this version 👍
