### ISSUE TITLE
Clipy crashes when excluding MacPass

### ISSUE THREAD

**Issue by normsu** [Clipy/Clipy#157]
Clipy 1.1.3 crashes when attempting to exclude MacPass (https://github.com/mstarke/MacPass).

Crash report:
[Clipy.txt](https://github.com/Clipy/Clipy/files/821447/Clipy.txt)

**Comment by Econa77** [comment]
@normsu Thanks for the report 👍 I think this is the same problem as #153 #144 

I will fix it for the next release 🚀

**Comment by ngehlert** [comment]
still happening for me. when will the next release be?
