### ISSUE TITLE
"Paste as plain text" format error ?

### ISSUE THREAD

**Issue by ulyssesric** [Clipy/Clipy#161]
"Paste as plain text" function works fine in TextEdit, Pages, Keynotes, and Microsoft Word 2016, but failed to work in Microsoft PowerPoint 2016. I don't know where the problem is, but it seems that "paste as plain text" failed to set the content data type of system clipboard from RTF to plain text. 

For example, when I copy some content from browser, the original content of system clipboard may look like this:

![screen shot: original content of system clipboard](https://cloud.githubusercontent.com/assets/914435/24285072/663be8f0-10a9-11e7-8340-da3932485da8.png)

The original content of system clipboard is RTF right now. After paste it into TextEdit with CMD key down, the content of system clipboard is supposed to be replaced by plain text, but as show in the screenshot below, it's still **RTF**, not plain text. And the content does not show correctly.

![screen shot 2017-03-24: system clipboard after CMD+Click in Clipy](https://cloud.githubusercontent.com/assets/914435/24285117/97bc68b4-10a9-11e7-887a-d3ab34182b84.png)

ClipMenu 0.43 won't have such problem. The content of system clipboard is correctly set to plain text after CMD+Click.

![screen shot 2017-03-24: system clipboard after CMD+Click in ClipMenu](https://cloud.githubusercontent.com/assets/914435/24285139/adf6539c-10a9-11e7-90ac-9407bc6a80b3.png)

Guess it would be a bug.

**Comment by Econa77** [comment]
@ulyssesric Thank you for the report.

I will find the bug and fix it in the next release 🚀

**Comment by omsrisagar** [comment]
I am facing the same issue as well in powerpoint (Mac). Paste as plain text pastes nothing.
