### ISSUE TITLE
「メニューに表示する文字数」→「メニューの表示幅」

### ISSUE THREAD

**Issue by knoajp** [Clipy/Clipy#167]
現状で「メニューに表示する文字数」は英数字も日本語もすべて1文字ずつ数えているようですが、文字の幅に大きな差があるため、メニューの表示幅を有効活用できていません。
そこで、文字数で指定するのではなく、ピクセルなどで幅を指定できるとうれしいです。

次善策としては、バイト数などを考慮するという選択肢があれば、いくらか緩和されると思います。

お読みいただきありがとうございました。

**Comment by Econa77** [comment]
@knoajp こちらは今後の改善案には入っておりますがなかなか綺麗に表示することができませんので実験中です。
アップデートまでもう少し時間がかかると思いますので気長にお待ちいただけると嬉しいです 🙏

**Comment by knoajp** [comment]
ありがとうございます。
表示幅が短くなりがちで気になる半角英数字は、プログラミングのコードだったりすることも多いので、
個人的には等幅フォントが選べればむしろそれがベストかなと、いまふと思いました。
(その場合も、文字数で指定するなら全角と半角の数え方は変えないといけませんが)
