### ISSUE TITLE
選択時におけるキーバインドについて

### ISSUE THREAD

**Issue by psato** [Clipy/Clipy#180]
履歴,スニペット選択の際，Emacsキーバインドの

上 C-p (Previous LineのP)
下 C-n (Next Lineのn)
左 C-b (backwardのb)
右 C-f (forwardのf)

のような操作ができると選択が簡単になり，ありがたいです．
また，vi系であるような，

C-{

でClipyから抜ける(esc)という機能があると良いと感じました．

**Comment by Econa77** [comment]
@psato 現状メニューにmacOS標準以外のキーバインドを追加する実装はメンテナンスコスト等を考えた結果実装する予定はありません。
提案をしてくださる人が増えれば考慮していきますので、現状は今のos標準の挙動でお使いください。
