### ISSUE TITLE
Keychain Access can not be exclude (Clipy crashing)

### ISSUE THREAD

**Issue by dennissieben** [Clipy/Clipy#181]
I tried to exclude the MacOS Keychain Access application to avoid storing password. Unfortunately this is not possible as it's greyed out in the file browser.

**Comment by dennissieben** [comment]
I have to update this issue. It's only greyed out if you search for the Keychain Access application. If you select it in the Utilities folder Clipy just crashes.

**Comment by Econa77** [comment]
@dennissieben Sorry for late reply. I think this is the same problem as #153 #144 #153 
It takes time to fix it but we will fix it in July 💪
