### ISSUE TITLE
[Feature request] Display menu at text cursor position

### ISSUE THREAD

**Issue by luispinadev** [Clipy/Clipy#183]
I was wondering if it was possible to add an option to display the menu at the text cursor position instead of the mouse pointer position.   

I find it quite confusing that Clipy displays the menu at the mouse pointer position, which usually is in some random spot in the screen when writing.
That's the way ClipMenu used to work b.t.w. (I may be mistaken about that though ;-) )

P.S. Thanks for maintaining this app, it's really wonderful!!

**Comment by Econa77** [comment]
@luispinadev Thank you for a wonderful suggestion.
I would like to realize this, but it is difficult to get the position of the text cursor in the current macOS system. I will investigate in the future whether it is feasible, but it seems to be difficult soon.

Thank you for using Clipy. I will do my best to make Clipy better 😄
