### ISSUE TITLE
Feature request: Option to not copy pasted item to clipboard

### ISSUE THREAD

**Issue by lucasvieites** [Clipy/Clipy#184]
Hi,
I'd like to see a feature that removes a pasted text from the clipboard History menu right after pasting. For example; you have a password in the Snippets and currently if you use the Snippet to paste the password it will appear in the clipboard History. If you use the History later to paste something else the password is visible in clear text for anyone to see. If someone is sitting with you they will see the password.
Would it be possible to add a check box or similar to specific Snippets to avoid them being added to History?

Thanks,
Lucas Vieites

**Comment by Econa77** [comment]
@lucasvieites Removal after pasting and management of history will be released in the future. Please wait a little more 😉 

Currently, you can manage the application to exclude copying on the setting screen, please exclude applications like 1Password and try using it.

**Comment by cachrisman** [comment]
I just tried doing this and it crashed when I clicked the add button after selecting the 1Password 6 app

Running Clipy v1.1.3 on macOS Sierra 10.12.5

**Comment by Econa77** [comment]
@cachrisman I'm sorry.
In the latest version of the English environment, it crashes after setting.
fixed #185 .

Please wait for a modified version to be released in the next month.

**Comment by Econa77** [comment]
@lucasvieites @cachrisman We fixed this issue and released [v1.1.4](https://github.com/Clipy/Clipy/releases/tag/1.1.4) 🎉

Thanks create issue 👍
