### ISSUE TITLE
Paste Entire History

### ISSUE THREAD

**Issue by shammellee** [Clipy/Clipy#187]
It would be cool to paste the entire history delimited by a newline.

**Comment by Econa77** [comment]
@shammellee There is no plan to implement the function to paste all the history by newline.
However, since the history export function will be implemented in the future, please substitute with it.

Thanks 👍

**Comment by shammellee** [comment]
Cool!

**Comment by tengattack** [comment]
Need this feature!
Or if there are some files store the entire history we could make a copy by ourselves?
