### ISSUE TITLE
changes in preferences only take place the next time an item is copied

### ISSUE THREAD

**Issue by tessus** [Clipy/Clipy#188]
Great app. Unfortunately I'm still getting used to Swift thus I can't make code changes myself and send a PR.

I've noticed that if you make changes in the preferences pane, they are not reflected right away.
e.g. uncheck or check `Mark menu items with numbers`

The menu still shows the old setting, until you copy another item into the clipboard.

This should be an easy fix. I was looking for a function that does something like updateMenu, but couldn't find anything. This should be a quick fix.

Any chance you could update the menu as soon as you make changes to the preferences pane?

**Comment by Econa77** [comment]
@tessus I think that is better as well.
I think that it can be easily modified, so I will try to fix it later.

Thank you for the report 😄

**Comment by tessus** [comment]
Great, thank you. I wish I could be of more help. I'm still using Obj-C and haven't made the transition to Swift yet.

**Comment by Econa77** [comment]
@tessus Thank you 😄 
Fixed this problem with #190 . It will be reflected in the next update.

We will welcome your contribution at any time 🚀
