### ISSUE TITLE
重複する履歴について

### ISSUE THREAD

**Issue by wakuya** [Clipy/Clipy#19]
はじめまして。
「ClipMenu」を愛用しておりますので、後継アプリの開発、とても嬉しく思っております。

さて、以前から思っていたことなのですが、
重複する履歴（テキスト）を一覧に表示できませんでしょうか？
（順にテキストをコピペしていきたい場合など、同じテキストがあると順番が1つ飛ばされてしまうため）

ご検討よろしくお願い致します。

**Comment by Econa77** [comment]
確かにそのような使用方法はありえる方法ですね。
次のバージョンにて設定画面に重複する履歴を保持するかどうかの設定を付けさせていただきます。

実装はまでしばらくお待ち下さい。

**Comment by wakuya** [comment]
ありがとうございます！
期待しております‼︎

**Comment by Econa77** [comment]
先ほどv1.0.5をリリースしました。
設定画面→メニュー→`重複した履歴を上書きする`のチェックマークを外すと上書きではなく新規の履歴としてコピーされます。

今後もClipyをよろしくお願い致します。
また、ご要望等ありましたらぜひご連絡ください
