### ISSUE TITLE
error when trying to build a Release version

### ISSUE THREAD

**Issue by tessus** [Clipy/Clipy#192]
I get the following error, when I try to build a `Release` version (the debug binary is 47 MB compared to the release binary which is 24 MB):

`
No profile matching 'ClipyDistribution' found:  Xcode couldn't find a profile matching 'ClipyDistribution'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
`

**Comment by Econa77** [comment]
Since my certificate was required for release build, I deleted settings by #198 .
I think that you can create release binaries with this, so please try it.

**Comment by tessus** [comment]
yes, it worked. thank you.
