### ISSUE TITLE
[Feature Request] show a larger image preview as tooltip

### ISSUE THREAD

**Issue by tessus** [Clipy/Clipy#193]
One can choose the size of the image in the menu/history. But it makes no sense to actually use a large image in the menu.

However, it would be a nice feature, if the menu item's tooltip were to show a larger version of the image.

What do you think?

**Comment by Econa77** [comment]
@tessus I think custom tooltip is a wonderful feature.
Implementation will be a while later, but I will implement it in the future 👍 

Thank for your request.

**Comment by tessus** [comment]
Thank you for looking into it.

**Comment by tessus** [comment]
Just wanted to follow up and ask about the status.

**Comment by tessus** [comment]
Project dead.
