### ISSUE TITLE
メニュー項目選択時の動作(コピーとペースト)

### ISSUE THREAD

**Issue by knoajp** [Clipy/Clipy#196]
現状の設定には

[v] メニュー項目選択後に "⌘ + V" を入力

というチェック項目があり、これは「メニュー項目選択時にまず選択項目がコピー(⌘+C)される」前提になっていると思いますが、これを

メニュー項目選択時
  [ ] 選択した項目をクリップボードにコピー
  [v] 選択した項目をその場にペースト

というように任意選択にすることで、「メニュー項目選択時に(クリップボードを経由させず)選択項目をその場に貼り付ける」ことができるとうれしいです。

具体的には、JavaScriptを書いていてスニペットとして登録してある "(function(){})();" をメニュー項目から選択したとき、続けざまに「さっきコピーしておいた function の中身」を貼り付けたいのですが、その時点でクリップボードの中身がいま貼り付けた "(function(){})();" になってしまっているのがもどかしく感じるのです。

ひるがえってみれば、個人的にはClipyの履歴メニューから何かを選択したときに、わたしが望むのはその項目がその場で貼り付けされることであって、その項目がさらにクリップボードにもコピーされていてうれしいシーンは思いつきません。

「(クリップボードを経由させず)」という動作は、クリップボード履歴アプリのやるべきこととしてどうなんだという気もしますが(苦笑)、ご一考いただければ幸いです。

**Comment by knoajp** [comment]
"履歴"メニューを選択したときの動作は変えずに、「"スニペット"メニューから選択した場合はクリップボードをいじらず、そのままテキストがその場に貼り付けられる」という動作(を可能にする設定項目)でもよいかもしれません。

**Comment by Econa77** [comment]
@knoajp 返信遅くなりすいません。
「設定」→「メニュー」→「重複した履歴をコピーする」のチェックを外すことで、一度メニューにはいった履歴がメニュー上部に来ることがなくなりますので、一番動作的には近くなるかと思いますので、一度お試しください。

スニペット選択時や履歴選択時に新たにメニューに追加されないようにするという機能の要望はよくお受けしておりますので、今後実装予定です。

ご意見ありがとうございます 👍

**Comment by knoajp** [comment]
なるほど。
スニペットを貼り付けた時点で「記憶する履歴の数」の制限内に同じスニペットがあれば、メニュー上部には来なくなるというわけですね。
現状は100に設定していますが、これを1000とか10000にすれば…

…と思いましたが、10000にしちゃうと(程度の差はあれ100であっても)、たとえばWebフォームで住所なんかをコピーしたときに、大昔のコピー履歴が邪魔して不幸な事態になりそうです。コピーする際に履歴10000項目との重複チェック処理が走るのも、(たとえコピー内容そのものをキーにしたハッシュテーブル検索にせよ、)気分よくないですね(笑)。

過去ログ確認はしたのですが、既出の要望だったとは、お手を煩わせすみませんでした。
実装を気長にお待ちしております。ありがとうございました!!
