### ISSUE TITLE
Delete individual history items

### ISSUE THREAD

**Issue by CrisVM** [Clipy/Clipy#197]
I've been a __ClipMenu__ user for years and I was really disappointed to learn it's no longer being developed, but then I just found __Clipy__ today and it's really amazing. I'm glad you're bringing new features to this already great app.

But there's one thing I'm really missing while using Clipy: the ability to delete individual history items.

On ClipMenu, I was used to Control + click _(this is customisable under the Action tab)_ an item to remove it. This is useful to avoid the clutter when you just copy the wrong text, image etc...

Maybe you could add this option to the Beta tab, just like the Plain text option _(which is also great BTW)_.

Thanks in advance and keep up the good work you've done so far.

_PS. Sorry if someone else has already asked for this, but I really can't read Japanese... Even my English skills aren't that great. My first language is Portuguese 'cause I'm Brazilian..._

Cheers.
Cristiano.

**Comment by Econa77** [comment]
@CrisVM Thank you for using Clipy.

Deleting history is the current top priority implementation function. Please wait for a while until the release.

No problem 👍 Please create the issue without worrying if you want the features.

Thanks 🍺

**Comment by CrisVM** [comment]
Awesome!

Thanks for replying. I'm really glad to know you're going to implement this feature. 👍

Rgds.

**Comment by Econa77** [comment]
@CrisVM We added the delete history function and released [v1.1.4](https://github.com/Clipy/Clipy/releases/tag/1.1.4) 🎉 

Thanks create issue 👍

**Comment by CrisVM** [comment]
Awesome! I've upgraded Clipy to v1.1.4 and it works great!
Thank you very much.

**Comment by prasadbiarca** [comment]
I am using Clipy and it is very good, except below 2 points
1. Not able to disable history menu(if I want to have only Snippet). Because when I click on snippet it copies a string which can be a password also, which in turn places in History as a clipboard.  
2. When I place my cursor on a snippet, it displays string stored in snippet. It is again a problem if it is a secret.

Is there any option which I might have missed to look into or is there any plan to implement above features?

Thank you in advance

**Comment by TrentonAdams** [comment]
> Awesome! I've upgraded Clipy to v1.1.4 and it works great! Thank you very much.

Could you explain how it worked great?  I enable the option in the beta section, and still nothing works.  It seems to have a control key associated with it, such as command, shift, control, etc, but there's no indication on how the feature actually works.

**Comment by burmanp** [comment]
> 
<img width="447" alt="Screenshot 2023-07-31 at 10 40 30" src="https://github.com/Clipy/Clipy/assets/33839250/a1de3c42-cbd7-476f-97ec-e9b382deb0a8">


I was wondering the same. I've set my "Delete history" to Alt/Option. Then if I open the clips history and alt+click on them, they get removed. 
Hope it helps.
