### ISSUE TITLE
[Feature Request] Shortcut for Clear History

### ISSUE THREAD

**Issue by samaero** [Clipy/Clipy#202]
I have a Macro setup to invoke the "Clear History" functionality and I use it all the time; I think it'd make sense to have a user-definable key command for this (I use shift + cmd + c).

**Comment by Econa77** [comment]
@samaero Thanks for your feature request 👍  

I would like to be able to set the "Clear History" menu shortcut on the preference window like each menu shortcut setting. I will implement it to the next release 🚀

**Comment by samaero** [comment]
Awesome, thank you!
