### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by ahmadawais** [Clipy/Clipy#209]
I would love to move from ClipMenu to Clippy but I need a UI update.

The list of clipboard history has 1. 2. 3. whereas on Clipy it's 1 2 3 which seems like a part of the clipboard. I think putting a dot and making that number a bit gray would make the UI better.

**ClipMenu**
![](https://i.imgur.com/Z40h8z3.png)

**Clipy**
![](https://i.imgur.com/0Y4UmwN.png)

How can I contribute and help?

**Comment by Econa77** [comment]
@ahmadawais Thanks for using Clipy 👍 

Changing the text color is a bit difficult, but I'd like to add dot.
Thanks create issue 😄
