### ISSUE TITLE
履歴のソート順

### ISSUE THREAD

**Issue by wakuya** [Clipy/Clipy#21]
便利に使わせていただいております。

ClipMenuにありましたオプションで、
履歴のソート順の実装は可能でしょうか？

現状では使用した履歴が一番上にきますが、
コピーした順のママ、固定できれば…。

ご検討よろしくお願い致します。

**Comment by Econa77** [comment]
ご意見ありがとうございます。

ソート機能に関しましては次回以降のアップデートにて対応させていただきます。
次回のバージョンアップは　
* #19 
* #20 
* その他バグ修正

を行う予定ですので、今しばらくおまちいただければと思います。

**Comment by wakuya** [comment]
『重複した履歴の上書き』のオプションに加え、重ね重ねありがとうございます。

**Comment by Econa77** [comment]
こちらもv1.0.6にて実装させていただきました。
アップデートまで今しばらくお待ち下さい
