### ISSUE TITLE
改行してコピー機能

### ISSUE THREAD

**Issue by kingtosh** [Clipy/Clipy#216]
もう一つ提案がありましたので、別のissueにしました。
一番上のクリップに対して、改行してコピーする機能をつけていただくことは可能でしょうか？
○○○
↓
×××をコピー
↓
○○○
×××　となるという感じです
ブラウザの拡張ではたまにこういう機能のものがあります。ご検討くださいませ。

**Comment by Econa77** [comment]
@kingtosh 申し訳ありませんが、コピー側の機能をあまり複雑にしたくないためこの機能の実装はあまり考えていません。
参考までにブラウザ拡張の名前等わかりましたら教えてくださいませんか？

**Comment by kingtosh** [comment]
Firefoxのアドオンですけど、AddMoreTextToClipboardというのがそれです。
https://addons.mozilla.org/ja/firefox/addon/addmoretexttoclipboard/
