### ISSUE TITLE
エクセルのデータをコピーしてもクリップされない

### ISSUE THREAD

**Issue by net9240** [Clipy/Clipy#224]
エクセルのデータをコピーしてもクリップされなくなりました。
同機能のクリップボード拡張ソフトで試してみましたが、他のソフトではクリップされますので、
不具合と考えられます。修正をお願いします。

**Comment by net9240** [comment]
追加情報
OSは、MacOS　HIGH　Sierra
エクセル　Ver.16.6

**Comment by Econa77** [comment]
@net9240 報告ありがとうございます。こちらでも同じ状態で確認させていただきます。
確認させていただきたいのですが、テキストのみの通常の場合でもコピーできない感じでしょうか。

**Comment by net9240** [comment]
お世話になっております。
テキストのみのコピーでは問題ありません。
よって、現状では、Excelでコピーし、テキストエディタにペースト、ペーストしたものをコピーすることで、履歴に記録しして使用しております。

**Comment by net9240** [comment]
いろいろ試してみまして、原因は、Excelの方にあるようなので、ご連絡します。
Office　Insiderに参加してアップデートすると、症状が発生することがわかりました。
今後正式アップデートされた際、症状が発生する可能性はあると思われます。
ご迷惑をおかけしました。
