### ISSUE TITLE
Restore icon to menu bar

### ISSUE THREAD

**Issue by cmgdev** [Clipy/Clipy#226]
I cleaned up my menu bar several months ago, and selected the option to hide Clipy. Is there a way to get it back?

The shortcut for clipboard history still works. But I cannot get to the snippets manager or any preferences.

I am using homebrew cask, and have tried uninstalling and reinstalling, but the icon is still gone from the menu bar. Any suggestions to get it back, or launch preferences?

**Comment by Econa77** [comment]
@cmgdev Have you changed the shortcut on the main menu? If you have not changed shortcut, you can try `⌘ + Shift + v`.

If you changed shortcut please reset setting by executing the following command and restart Clipy.
`defaults delete com.clipy-app.Clipy`

**Comment by cmgdev** [comment]
@Econa77, I had changed the shortcut, but none of the other shortcuts were working either.

Running `defaults delete com.clipy-app.Clipy` fixed it though. Thanks!
