### ISSUE TITLE
Edit snippets option leads to blank folder

### ISSUE THREAD

**Issue by puranzhang** [Clipy/Clipy#228]
After a while not editing snippets, when click on the ```Edit snippets...``` option in the menu, it always shows a edit window with blank folder as shown:
<img width="912" alt="screen shot 2017-10-17 at 16 53 09" src="https://user-images.githubusercontent.com/9508376/31694877-ab6e8ed2-b35b-11e7-93d5-1706422f3358.png">
The only to escape this is clicking ```Add Folder```, which brings up new untitled folder and my saved folder (shortcut in my case):
<img width="912" alt="screen shot 2017-10-17 at 16 54 34" src="https://user-images.githubusercontent.com/9508376/31694934-026e7d32-b35c-11e7-9e58-05263d96385f.png">
It's a bit trivial to do this "add and delete" every time. Thanks for investigating this.

**Comment by Econa77** [comment]
@puranzhang Thanks report 👍 
This problem is a problem with macOS HighSierra and has been fixed in #218 

I am investigating whether there is another problem at HighSierra now, so I will release it as soon as it is completed 🚀

**Comment by Econa77** [comment]
@puranzhang I fixed this issue and released [v1.1.5](https://github.com/Clipy/Clipy/releases/tag/1.1.5) 🚀 
Please try this version 👍
