### ISSUE TITLE
重複した履歴の上書きオプションについて

### ISSUE THREAD

**Issue by wakuya** [Clipy/Clipy#23]
いつも便利に使わせていただいております。

1.0.5で追加された重複した履歴の上書きオプションですが、
ペースト後、履歴の表示にバグがあるようです。
※履歴の上にペーストしたデータが移動しますが、下にも残ってしまっていてペーストするごとに履歴が増えていきます。

ご確認よろしくお願いします。

**Comment by Econa77** [comment]
ご連絡ありがとうございます。

現状の実装はペーストデータを残すようになっていますので、バグではなく仕様となっています。
同じ履歴があればコピーしない等の設定は次回以降のアップデートにて実装させていただきます。

**Comment by Econa77** [comment]
v1.0.6にて実装させていただきました。
アプリの更新はその他バグの修正が終わりしだい行いますのでいましばらくお待ち下さい :smile:
