### ISSUE TITLE
スペニット編集の内容表示に関して

### ISSUE THREAD

**Issue by net9240** [Clipy/Clipy#231]
スペニットに登録している情報がある状態で、スペニット編集を実行すると、登録済みの内容が表示されません。フォルダ追加をクリックしないと表示されません。

**Comment by comomac** [comment]
Probably related to #217 

多分 #217 に関連するでしょう

**Comment by Econa77** [comment]
@net9240 @comomac  遅くなって申し訳ありません。
先程こちらの問題を修正した [v1.1.5](https://github.com/Clipy/Clipy/releases/tag/1.1.5) をリリースしました。
報告ありがとうございました 👍
