### ISSUE TITLE
Feature request: full list of pasted items

### ISSUE THREAD

**Issue by niccolomineo** [Clipy/Clipy#233]
Hi, do you think it could be worth allowing the user to select between a "folder" list view (like it is now) and a simple "all items" view (in Pastebot's fashion)?

**Comment by niccolomineo** [comment]
I see this can be partially solved by specifying a number of elements in the Main Menu History.
The problem is that, if the amount of pasted elements exceeds that number I specified, a folder is appended. Could this be avoided?
An example could be that if the user specifies 20 elements in the Main Menu History and enters 0 elements in Folder, then he would be able to see just the list of the latest 20 pasted elements with no folders appended.

**Comment by samaero** [comment]
Could you just set the "Number of items place inline" setting to something really high, say 1000, so that you'll never hit that limit before it starts appending a folder?

**Comment by niccolomineo** [comment]
Hi, wouldn't it be better, for reasons of security and system performance, to be able to enter the capping manually, instead of throwing in a very high number (which feels hacky, too) for the inline items?
