### ISSUE TITLE
MacOS High Sierraで、スニペット編集画面にスニペット一覧が表示されない

### ISSUE THREAD

**Issue by funghiini** [Clipy/Clipy#235]
編集はできませんが、データのエクスポートはできるようです。

**Comment by funghiini** [comment]
#217で解決済みですね！あとはアップデート機能でアップデーツできるようにするだけですね。

**Comment by Econa77** [comment]
@funghiini 遅くなり申し訳ありません。
先程 [v1.1.5](https://github.com/Clipy/Clipy/releases/tag/1.1.5) をリリースして修正しました。
