### ISSUE TITLE
Dvorak配列使用時に"⌘ + V"が入力されない不具合

### ISSUE THREAD

**Issue by takamu** [Clipy/Clipy#258]
私はMacBook Pro (Retina, 13-inch, Early 2015)、macOS High Sierra(10.13.3)を使用しております。

キーボードをDvorak配列に設定しているのですが(システム環境設定→キーボード→入力ソース から）
このときにClipyの「メニュー項目選択後に"⌘ + V" を入力」にチェックを入れていると不具合が発生します。

キーボードの配列を変更しているためか、実際にメニュー項目を選択すると、⌘ + Vではなく ⌘ + K が入力されてしまうのです。（QWERTY配列におけるVの位置が、Dvorak配列におけるKなのです）

こちら、ご修正いただければ幸甚にございます。

**Comment by Econa77** [comment]
@takamu 対応遅れてしまいすいませんが、Dvorak配列時にペーストコマンドが正しく入力されない問題を #298 で対応しました。
次回のリリースで対応されます 👍
