### ISSUE TITLE
[Feature Request] Gist integration for Snippets

### ISSUE THREAD

**Issue by Campano** [Clipy/Clipy#261]
It would be soooo helpful to be able to have a gist integration, so you could add a gist repo as a snippet folder

It would bring the following features:

- backup 
- add / share / contribute to libraries of snippets

**Comment by MoonshineSG** [comment]
It sure would be awesome... but.... https://github.com/Clipy/Clipy/issues/221

**Comment by Campano** [comment]
Oh that's too bad... Thanks for replying.
