### ISSUE TITLE
1Password 7 Mini Exclusion

### ISSUE THREAD

**Issue by ammmze** [Clipy/Clipy#278]
So I'm just barely jumping to this app from the original ClipMenu in hopes that I can finally exclude 1Password Mini from my clip history. I saw in #149 that support was added for it. Looking at the code we are just automatically excluding it? Or is there something I need to do to get that working? I've added 1Password 7 to the list, but that doesn't catch 1Password mini. Perhaps the namespace has changed in 1Password 7 vs 1Password 6 where the change was applied before.

**Comment by Econa77** [comment]
@ammmze Sorry for the late response 🙇 We supported to 1Password 7 and extensions with #291 

We will release the latest version during this month 🚀
