### ISSUE TITLE
How to backup clipy snippets?

### ISSUE THREAD

**Issue by donnlee** [Clipy/Clipy#293]
I searched open+closed issues for 'backup' but didn't find any recipe for backing up my Clipy snippets.  Anyone know the file containing the snippets?  Can the file be backed-up and simply restored in the event of a laptop restore?

**Comment by martinandersen3d** [comment]
From trying to read the source.. I guess.. I have found the folder:

/Users/<username>/Library/Application Support/Clipy

there is some .data files here... but don't know how they work... but when I open them, they do contain some of my own snippet text :-)

**Comment by martinandersen3d** [comment]
Also on the toolbar there is the Import/export buttons

**Comment by donnlee** [comment]
Ah, click toolbar icon, "Edit snippets...", then click Export icon in toolbar of the "Snippets Editor"
Thanks!

**Comment by timlance** [comment]
Thanks you, donnlee! I probably would have noticed that. Sometime in the next millennium.
