### ISSUE TITLE
２台以上でスニペットを共有する方法

### ISSUE THREAD

**Issue by object-kazu** [Clipy/Clipy#30]
２台以上のMACでスニペットを共有する方法が
あるのなら、ReadMeに記載して欲しい。

**Comment by Econa77** [comment]
連絡おそくなりすいません。
現状同期機能は実装しておらず、案内することはできません。

今年半ばにはAppStoreへリリースし、iCloudやdropboxでの同期機能を実装させていただきますので、今しばらくお待ちいただければと思います。
