### ISSUE TITLE
Not work in mojave 10.14.4

### ISSUE THREAD

**Issue by neowood** [Clipy/Clipy#362]
My OS is mojave 10.14.4, and I'm using clipy v1.2.1, I have also set the accessibility in privacy, but after I copied some texts, the history stayed empty. I have tried reinstall clipy, restart mac... but none of them worked. Are there any other settings? Thanks!

**Comment by mlaigre** [comment]
Works for me after upgrading to 10.14.4 with default configuration

**Comment by neowood** [comment]
I cleaned the configurations with app cleaner, then reinstalled, and it worked, thanks!
