### ISSUE TITLE
Have this project been abandoned?

### ISSUE THREAD

**Issue by chenxiccc** [Clipy/Clipy#368]
Have this project been abandoned?
Hasn't been updated for a long time, and the major bug #319 has not been fixed yet.

**Comment by TristenChenTao** [comment]
same question

**Comment by ian4hu** [comment]
I just maintain a fork  of this at [https://github.com/ian4hu/Clipy/releases](https://github.com/ian4hu/Clipy/releases) , and released with fixed #319

**Comment by thierryH91200** [comment]
@ian4hu thanks

**Comment by borekb** [comment]
Fingers crossed, @ian4hu, really happy to see things like search on your roadmap.

**Comment by ryan-winkler** [comment]
@ian4hu Have you tried messaging the maintainers of Clipy to see if they can add you to the project? @Econa77 @econa @jcw- @ericyahhh  @andrew-codechimp @thii @piamancini 

Any help here?
