### ISSUE TITLE
[Request] Make possible to pin values

### ISSUE THREAD

**Issue by protiumx** [Clipy/Clipy#369]
Hi! Thank you for this awesome open source utility.
I'm new on Mac, I come from Linux Gnome env where I had a similar utility.
The feature I really miss is the possibility to pin/fav/star values to the top of the menu, hence I always have my frequently used commands at the top.

I've read the documentation and didn't find any configuration to make this possible.

Thanks in advance!

**Comment by illus0r** [comment]
I like the way how it is implemented in iPaste. Pinned items are at the bottom. When I press Alt, the pin icons appear so that items can be pinned or unpinned:

![ipaste](https://user-images.githubusercontent.com/797993/78158626-8d995d00-7452-11ea-99d6-24b75c46713c.gif)
