### ISSUE TITLE
Cann't open Clipy main menu

### ISSUE THREAD

**Issue by lovelock** [Clipy/Clipy#386]
I set a new shortcut for history and hide the app both in dock and on menu. Now I want to change the column size of history but Clipy main menu just disappeard. I reinstalled it and nothing worked. 
Or where can I find the configuration path I can delete all the config files and maybe the main menu would come back again.

**Comment by theMajc** [comment]
Same here. Found this: https://github.com/Clipy/Clipy/issues/382, but author closed it without solutions.

**Comment by lovelock** [comment]
After several times install and remove by home brew, it somehow appears again and I don’t know why actually, so I switched the icon on and never touch that switch again

**Comment by theMajc** [comment]
I installed https://github.com/ian4hu/Clipy, and after several content clear and reinstall, and it still did not work, but I guess at some point, I restarted my Mac, and Clipy reset itself, started to show the icon, as well as a "Preference" item in the main menu.

**Comment by syniuhin** [comment]
what worked for me:
```
13 22:30:18 Ψ brew cask rm clipy
==> Uninstalling Cask clipy
==> Quitting application 'com.clipy-app.Clipy'...
Application 'com.clipy-app.Clipy' quit successfully.
==> Backing App 'Clipy.app' up to '/usr/local/Caskroom/clipy/1.2.1/Clipy.app'.
==> Removing App '/Applications/Clipy.app'.
==> Purging files for version 1.2.1 of Cask clipy
13 22:30:25 Ψ rm -rf /usr/local/Caskroom/clipy
13 22:30:43 Ψ brew cask install clipy
```
Tried removing without removing the backup and I assume homebrew was just recovering from it.

**Comment by lovelock** [comment]
I've tried `brew cleanup` and nothing changed so maybe `cleanup` command does not cleanup the "backup"




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Illia (Eli)"<notifications@github.com&gt;; 
发送时间: 2020年1月14日(星期二) 中午11:37
收件人: "Clipy/Clipy"<Clipy@noreply.github.com&gt;; 
抄送: "王青春"<happyhackerwqc@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Clipy/Clipy] Cann&#39;t open Clipy main menu (#386)




what worked for me:
 13 22:30:18 Ψ brew cask rm clipy ==&gt; Uninstalling Cask clipy ==&gt; Quitting application 'com.clipy-app.Clipy'... Application 'com.clipy-app.Clipy' quit successfully. ==&gt; Backing App 'Clipy.app' up to '/usr/local/Caskroom/clipy/1.2.1/Clipy.app'. ==&gt; Removing App '/Applications/Clipy.app'. ==&gt; Purging files for version 1.2.1 of Cask clipy 13 22:30:25 Ψ rm -rf /usr/local/Caskroom/clipy 13 22:30:43 Ψ brew cask install clipy  
Tried removing without removing the backup and I assume homebrew was just recovering from it.
 
&mdash;

**Comment by syniuhin** [comment]
@lovelock "backup" as of:
> ==> Backing App 'Clipy.app' up to '/usr/local/Caskroom/clipy/1.2.1/Clipy.app'.

**Comment by lovelock** [comment]
Yeah I noticed that, thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Illia (Eli)"<notifications@github.com&gt;; 
发送时间: 2020年1月14日(星期二) 中午11:53
收件人: "Clipy/Clipy"<Clipy@noreply.github.com&gt;; 
抄送: "王青春"<happyhackerwqc@foxmail.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Clipy/Clipy] Cann&#39;t open Clipy main menu (#386)




@lovelock "backup" as of:
  
==&gt; Backing App 'Clipy.app' up to '/usr/local/Caskroom/clipy/1.2.1/Clipy.app'.

**Comment by lsirivong** [comment]
For anyone else running into this where you didn't install via homebrew:

I was able to get the default preferences restored by deleting the file `~/Library/Preferences/com.clipy-app.Clipy.plist`

**Comment by sming** [comment]
> For anyone else running into this where you didn't install via homebrew:
> 
> I was able to get the default preferences restored by deleting the file `~/Library/Preferences/com.clipy-app.Clipy.plist`

@lsirivong  this isn't even working for me -_- 

Anyone know what else I have to nuke to get clipy back? I've lost my snippets hotkey and the ability to get to Preferences -_-

**Comment by Econa77** [comment]
@lovelock Sorry for the late reply. 
You can return to the initial settings by resetting the settings as in #226 #412 and then restarting.
