### ISSUE TITLE
[Feature request] Ability to persist items on top of clipboard

### ISSUE THREAD

**Issue by hellovietduc** [Clipy/Clipy#390]
I'd love to see this feature. I often have to copy some fixed texts over and over again, and they get down on the list quickly as I work. It's nice to have an option to keep the texts on top of the clipboard or in a separate section.

Thank you.

**Comment by dongyuwei** [comment]
@vietduc01100001  I think you can  just use the build in Snippets feature of Clipy. It's very useful.

**Comment by hellovietduc** [comment]
> @vietduc01100001 I think you can just use the build in Snippets feature of Clipy. It's very useful.

Oh my bad. I haven't used that feature. Thank you!
