### ISSUE TITLE
履歴が全く表示されなくなった。/プライバシーで権限付与済

### ISSUE THREAD

**Issue by makotoyamaya** [Clipy/Clipy#398]
OS10.15.4
Clipy 1.21
iMac Retina 5K Late2014
一般＜記憶する履歴の数 50項目

最近まで、Dropboxを利用して複数PCでのClipy内容の共有を行っていましたが、
不要になった為、ライトクリーナーアプリを利用し、すべてのClipyファイルを削除、
PCの再起動を行ってから、新規でClipyを追加しました。

残っていたプライバシーも削除、再度権限付与。

ですが、履歴が全く表示されません。

いろいろ試みたものの、原因不明です。
なお、別の同条件のPC(Macbook pro)では履歴が表示されています。

仕事にならないレベルで困っています。
どなたかご協力くださいませ。

**Comment by makotoyamaya** [comment]
自己解決しました！

どこの何のファイルが悪かったかは分からないものの、
App CleanerというアプリでClipyのファイルをすべて削除してから
再インストールした所、無事に履歴も出るようになりました。

Dropboxを利用して共通化しようとして困った方は、お試しください。

**Comment by Econa77** [comment]
@makotoyamaya ありがとうございます。おそらくUserDefault等のキャッシュが消えていなかったのだと思います。
解決策を書いていただきありがとうございます 🙇
