### ISSUE TITLE
メニューバーから削除したら、再度メニューバーに表示ができない

### ISSUE THREAD

**Issue by 55freak** [Clipy/Clipy#402]
Clipyを愛用しています。
開発ありがとうございます。

先日、誤って**メニューバーからClipyのアイコンを削除**してしまいました。

再度メニューバーに戻したいのですが、方法がわかりません。

ショートカットキーの変更やスニペット登録をしたいのですが、
メニューバーのアイコンがなく設定が開けない状態です。

一度アンインストールし、再度インストールしましたがダメでした。

対応頂けますと幸いです。

よろしくお願いします。

macOS Mojave 10.14.6
Clipy 1.2.1

**Comment by Econa77** [comment]
@55freak アンインストール時に設定ファイル等の削除ができていないのだと思います。 [AppCleaner](https://www.softantenna.com/wp/review/appcleaner/)　等を使用してアンインストールしてから再度インストールしてみてください 🙏

**Comment by 55freak** [comment]
回答ありがとうございます！

AppCleanerを使用→Macを再起動

で無事、戻りました。
感謝です。
