### ISSUE TITLE
[Feature Request] Direct access to most recent clips

### ISSUE THREAD

**Issue by rastriffler** [Clipy/Clipy#408]
Loving Clipy!  

It's great as it is, but was wondering if it might be possible to have the most recent (say...5? 10?) clips be immediately available when you hit ⌘-⇧-V, then have older clips collected in folders (as is currently the case).  Basically have the contents of what is currently the first folder appear in the menu without having to click on the folder.

While it seems like you're only reducing the number of key strokes/mouse clicks by 1, it actually makes the interaction much quicker and more intuitive.

**Comment by codeshif** [comment]
Do you mean this setting item, like this?
<img width="480" alt="截屏2020-06-07 上午8 41 49" src="https://user-images.githubusercontent.com/35602158/83957394-f1009a80-a89a-11ea-8434-5eddf199a0a2.png">

**Comment by rastriffler** [comment]
Yes, thank you!  That is exactly what I am looking for.  I had to clear my recent history in order for it to take effect, but it's working just as hoped now.

Thank you!
