### ISSUE TITLE
how to change the config after hide the icon?

### ISSUE THREAD

**Issue by NachoLiu1234** [Clipy/Clipy#412]
I hide the icon in menu bar and want to change the config, but I didn't set the hotkey to open the main panel. I even deleted the app and reinstall it again, but it doesn't work.

**Comment by jacob-labs** [comment]
Did you change the default hotkey? If not, it is `⌘+shift+v`.

**Comment by platoer** [comment]
Me too. If you hide the icon,you will lost it.

**Comment by cjahv** [comment]
Restore menu icon #226

**Comment by Econa77** [comment]
@cjahv Thanks 👍 
@NachoLiu1234 @platoer As you can see in #226, restart Clipy after executing the following command in `Terminal.app` to reset the settings.
`defaults delete com.clipy-app.Clipy`
