### ISSUE TITLE
メニューバーにアイコンが表示されない

### ISSUE THREAD

**Issue by krpk1900** [Clipy/Clipy#429]
設定を変更したいのですが、メニューバーにアイコンが表示されず、設定画面が開けません。
もしかしたら自分で非表示に設定したのかもしれませんが、設定画面を開く方法はありますか？

**Comment by Econa77** [comment]
@krpk1900 現状ではショートカットを忘れてしまってアイコンが表示されない場合は一度設定をリセットするしかありませんので、以下のissueのようにコマンドを実行後に再起動すれば再度表示されるようになるかと思います。
`defaults delete com.clipy-app.Clipy`

ref: https://github.com/Clipy/Clipy/issues/412#issuecomment-723546534
