### ISSUE TITLE
Can't build this project in my computer, does any can talk about the order the build

### ISSUE THREAD

**Issue by loyio** [Clipy/Clipy#442]
Using M1 Mac
macOS Big Sur Version 11.1
Xcode Version 12.3 (12C33)

1. I'm git clone this project to my local env.
2. and open `Clipy.xcodeproj`
3. I have change the build destination to Resetta and click the Build then report a error like `"No such module 'Sauce'"`
4. And then I opened `Pods.xcodeproj`, change the scheme to Pods-clipy
5. click the build get a Pods_Clipy.framework
6. add this to `Clipy.xcodeproj`
7. finally, this build failed

I am a novice in Mac developing, thanks for your help

**Comment by loyio** [comment]
error input
```
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/loyio/Library/Developer/Xcode/DerivedData/Clipy-cbqkftoeeqzrzseirqmxcqcdbzwr/Build/Intermediates.noindex/Clipy.build/Debug/Clipy.build/Script-07B47785AE0AC2185B570C28.sh (in target 'Clipy' from project 'Clipy')
    cd /Users/loyio/githubProject/Clipy
    /bin/sh -c /Users/loyio/Library/Developer/Xcode/DerivedData/Clipy-cbqkftoeeqzrzseirqmxcqcdbzwr/Build/Intermediates.noindex/Clipy.build/Debug/Clipy.build/Script-07B47785AE0AC2185B570C28.sh

mkdir -p /Users/loyio/Library/Developer/Xcode/DerivedData/Clipy-cbqkftoeeqzrzseirqmxcqcdbzwr/Build/Products/Debug/Clipy.app/Contents/Frameworks
/Users/loyio/githubProject/Clipy/Pods/Target Support Files/Pods-Clipy/Pods-Clipy-frameworks.sh: line 42: source: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by Econa77** [comment]
@loyio Open `Clipy.xcworkspace` to build the project. You can then build on your M1 Mac by selecting the `Clipy` scheme and` My Mac (Rosetta) `.

Cannot do a native build (not Rosetta) of the M1 Mac at this time, but I'm working on it.

**Comment by loyio** [comment]
@Econa77 
thank you for your answer
but I already does this step, and rebuild the framework adapt to the project
and I think my fail build is  caused by the `Pods_Clipy.framework`

my `Pods_Clipy.framework` is like this image below I'm uploaded

thanks

<img width="725" alt="Screen Shot 2021-01-01 at 9 27 19 PM" src="https://user-images.githubusercontent.com/32695256/103439494-6b01d200-4c78-11eb-94dd-68c895f5bf8b.png">

**Comment by Econa77** [comment]
@loyio `Pods_Clipy.framework` should be linked automatically. Would you please re-do `git clone` and open `Clipy.xcworkspace` to build the `Clipy` scheme in Xcode? 

Note that the file to open is `Clipy.xcworkspace` instead of `Clipy.xcodeproj`.

**Comment by loyio** [comment]
@Econa77 
Thanks for your help
I'm sorry that I didn't notice your first comment about the `Clipy.xcworkspace`

**Comment by Econa77** [comment]
@loyio 👍 The issue will close, but if you still have problems please reopen it.
