### ISSUE TITLE
Cannot build on M1 mac.

### ISSUE THREAD

**Issue by keisukeYamagishi** [Clipy/Clipy#453]
I can't build on M1 mac CPUs because they are not compatible.
There are about 100 errors in Realm. Some of them are listed below.

Undefined symbol: realm::ArrayBinary::set(unsigned long, realm::BinaryData)

This is due to CPU incompatibilities.

So you can solve this by adding `arm64` to the `Excluded Architectures` in Clipy

**Comment by kalafalas** [comment]
Theres a Apple Silicon beta build floating out in the wild, but it doesn't launch. maybe you could help?

https://github.com/ian4hu/Clipy/issues/57

**Comment by keisukeYamagishi** [comment]
Yes, it is possible.
My PC is an M1 mac, so I can verify this.

**Comment by keisukeYamagishi** [comment]
Hi there👋
I fixed it.
Check out bellow pull request
https://github.com/Clipy/Clipy/pull/457

**Comment by Econa77** [comment]
@keisukeYamagishi Thank you for the issue and PR 👍 

We have upgraded the dependency libraries so that it can be built on M1 mac ( #465 ).
