### ISSUE TITLE
Feature Request: Ability to pin records

### ISSUE THREAD

**Issue by luizanao** [Clipy/Clipy#455]
As an user I'd like to have some items pinned on my history (top or bottom) where I can store things I use ofeten.
```bash
*----------*
1. fixed item  
2. fixed item 
*----------* 
rest 1
rest 2
....
*----------*
```

thoughts?

**Comment by Sokrates1966** [comment]
Why don't you use the snippets? Is there a difference in the functionality you're looking for?

**Comment by luizanao** [comment]
I never really tried snippets out, that solves my case. thanks @Sokrates1966  nice tip
