### ISSUE TITLE
Clear entries individually

### ISSUE THREAD

**Issue by AntonioRedondo** [Clipy/Clipy#456]
Hi there,

Thank you for this extremely practical piece of software for macOS. 💝

I wonder if it would be possible to remove history entries individually by pressing some shortcut over the history menu when this is open. On the Windows Clipboard History menu you can remove entries by just pressing <kbd>del</kbd>.

<img width="148" alt="image" src="https://user-images.githubusercontent.com/5444421/110136057-2654fd00-7dc7-11eb-8b98-f1f585d414d9.png">

**Comment by qxxiao** [comment]
+1

**Comment by mntbighker** [comment]
This feature already exists in the "Beta" panel with a modifier key selection.

**Comment by AntonioRedondo** [comment]
I'm closing this issue because it's a duplicated of https://github.com/Clipy/Clipy/issues/431
