### ISSUE TITLE
Clipy 1.0.7 crash

### ISSUE THREAD

**Issue by Chamiu** [Clipy/Clipy#47]
[Clipy_2016-03-20-230813_MacBook-Pro.cpu_resource.diag.zip](https://github.com/Clipy/Clipy/files/181334/Clipy_2016-03-20-230813_MacBook-Pro.cpu_resource.diag.zip)

**Comment by Econa77** [comment]
ホットキー関連のクラッシュですが、 #78 のライブラリ置き換えで一端対応しました。
来月リリース予定のv1.1.0のリリース後に同様のクラッシュが見られるようでしたら再度報告していただけると助かります。

クラッシュログありがとうございました 😄
