### ISSUE TITLE
Naming snippets and folders

### ISSUE THREAD

**Issue by Addismedia** [Clipy/Clipy#485]
I have just installed Clipy and am very happy with it having used a similar program previously. However one feature I cannnot seem to fix is to name my snippets and folders which I used to be able to do with ClipMenu. Any ideas on how to do this? I simply get a series of "untitled snippet" which do contain the info I want to paste but I have to guess which is which!
Help or advise appreciated.

**Comment by Sokrates1966** [comment]
Just go to the Edit snippets section and there double click on any of your "untitled snippets" to rename them for your convenience.
You can also make yourself folders for your different kind of snippets that might go together.

**Comment by Addismedia** [comment]
Thank you very much for the quick and helpful reply. That works fine.
