### ISSUE TITLE
Keyboard navigation not working

### ISSUE THREAD

**Issue by a-lianos** [Clipy/Clipy#487]
MacOS Big Sur 11.6
MacBook Pro (16-inch, 2019)

I am bringing up the popup via a keyboard shortcut (Shift+cmd+V), but then neither the arrows nor the numbers work to select an option. No option is highlighted by default (not sure if there should be). I have to use the mouse to pick what I need. Let me know if I can help with any diagnostics.

**Comment by a-lianos** [comment]
This solved as per this post https://github.com/Clipy/Clipy/issues/476. Apparently the permissions are required because clipy needs to intercepts your keystrokes even though it does not become the active program. It would be useful if it would ask for it though!

**Comment by vtmocanu** [comment]
Thank you for posting this!

**Comment by seansmyth** [comment]
This issue is happening again? I have "Clipy" checked within the the Accessibility tab of Security and Privacy.
