### ISSUE TITLE
Add cask file to caskroom/homebrew-cask

### ISSUE THREAD

**Issue by shin1ogawa** [Clipy/Clipy#5]
I tried to created cask file `clipy.rb`. This works on my local environment.

```ruby:clipy.rb
cask :v1 => 'clipy' do
  version '1.0.0'
  sha256 '3bd648fb8fcd9a4fec00dd9c0f9de81840635203bee08444303e96db89aadb64'

  url 'https://github.com/Clipy/Clipy/releases/download/1.0.0/Clipy_1.0.0.dmg'
  name 'Clipy'
  homepage 'http://clipy-app.com/'
  license :mit

  app 'Clipy.app'
end
```

**Comment by Econa77** [comment]
Thanks for write cask file.

We should send a pullRequest to homebrew-cask.

**Comment by Econa77** [comment]
Changes have been incorporated
Thanks for your Contribution.

https://github.com/caskroom/homebrew-cask/pull/12354#issuecomment-118503470
