### ISSUE TITLE
Can't delete a particular history

### ISSUE THREAD

**Issue by naveenkraja** [Clipy/Clipy#522]
Now we have options for deleting the complete history but what if I wanted to delete one particular history say I have copied a password and I no longer want that to be in the history?

now am not able to clear that one particular entry from the clipboard. pls, let me know in case if someone has mentioned it somewhere else because I was able to see only clearing the whole history only.

Clipy v1.2.1
Ventura 13.1 (Macbook Air M1, 2020)

**Comment by dannylevenson** [comment]
Under Preferences go to the "Beta" tab. Click on the switch to activate "Delete History" and pick a modifier key. Now if you use that modifier to click on an entry in the UI, it will delete it.

**Comment by naveenkraja** [comment]
@dannylevenson great thanks it works
