### ISSUE TITLE
Screenshot to Clipy

### ISSUE THREAD

**Issue by j03ph** [Clipy/Clipy#525]
Hi there I have a question about screenshots.
Is there a way how to take screenshot with Shift+CMD+4 directly to Clipy. Not only to MacOS clipboard? Beta function - save screenshot in Clipy history is not working or I have something wrong set.
Thanks for reply.

**Comment by kethinry** [comment]
I have the same question. Have you already solved it?

**Comment by jskulski** [comment]
Been using clipy for many years and it was in the last year or so (Ventura maybe?) it stopped working- never investigated but would love it back. It was a very useful feature.

**Comment by phrend** [comment]
I continue to use v1.1.5 because it still supports screenshots.

**Comment by j03ph** [comment]
> I continue to use v1.1.5 because it still supports screenshots.

Holly moly that's it! Thank you!
