### ISSUE TITLE
Clipy crashes on opening preference.

### ISSUE THREAD

**Issue by Canorus** [Clipy/Clipy#57]
Clipy crashes on opening preference panel when icon is hidden on menu bar. I have a crash report generated but cannot find appropriate way.

**Comment by Econa77** [comment]
@Canorus 

Thakns for using clipy.
Crash on english preferences bug is fixed version 1.0.9.
If you using version 1.0.8, please update clipy.

https://clipy-app.com
or
https://github.com/Clipy/Clipy/releases/tag/1.0.9

Please message again if the crash using the latest version

**Comment by Canorus** [comment]
Oh, didn't notice there was a new version available. Problem  solved. Thank you so much :D
