### ISSUE TITLE
ショートカットのダブルタップ対応

### ISSUE THREAD

**Issue by essuzuki** [Clipy/Clipy#61]
* ダブルタップのショートカットに対応する予定はあるのでしょうか
 * Alt2連打やCtrl2連打など

**対応したらAlfredから乗り換えたい...**

**Comment by Econa77** [comment]
ショートカット機能の強化は早いタイミングで実装予定です。
まずは現状できていないショートカットの割り当てなしの実装を行いますが、ダブルタップもその際実装出来ないか確認してみます。

最終的にはAlfredのようなショートカット設定を目指していますので、時間はかかりますが実装をお待ちいただければと思います。

**Comment by essuzuki** [comment]
楽しみに待ってます :)

**Comment by essuzuki** [comment]
🙇
