### ISSUE TITLE
スニペット登録時の"（ダブルクォーテーション）がおかしい

### ISSUE THREAD

**Issue by michek093538** [Clipy/Clipy#71]
いつも愛用しています。

例えば、スニペットに<a href="" "" ></a>を登録しておくと、
登録した瞬間に<a href=“””” ></a> となってしまいます。

よくみるとわかりますが、"（ダブルクォーテーション）が変わっています。
こちらの画像も参照願います。
https://www.evernote.com/l/AAJwaDNQaoBM2bTBBy1tQaWV9BhIDvJFbLk

そのため、ちょっとタグを入れ込みたい場合に使えません。
よろしければ修正をお願いします。

また、可能であれば次のようなアクションができればベストです。

http://xxxxxxx.com/ と書いてあった場合に、
対象の文字列を選択して、スニペットを起動すると、
対象文字列がタグに挟まれた状態で貼り付けられる。

ご検討ください。

**Comment by Econa77** [comment]
@michek093538 
Clipy使用していただきありがとうございます。

ダブルクォーテーションの件こちらでも再現することができました。
次のバージョンアップにて修正させていただきます。

アクション機能に付きましても時期は明言できませんが、今後のアップデートにて追加させていただく予定です。
実装は今しばらくお待ち下さい。

**Comment by michek093538** [comment]
ありがとうございます。
楽しみにしてます。
